// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsCrypto "github.com/acme-kuetix/acme-std-crypto/modules/crypto/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["crypto"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"crypto"+"/"+"crypto", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "crypto", Impl: transitionsCrypto.NewCryptoTransitions() }})
	}
}
