// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/engine/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"crypto": {
			"crypto": {
				"Hash": {
					GoModule: "github.com/acme-kuetix/acme-std-crypto",
					ModulePath: "modules",
					FilePath: "modules/crypto/transitions/crypto.go",
					Namespace: "crypto",
					Class: "crypto",
					Name: "Hash",
					NumIn: 1,
					NumOut: 1,
					ArgTypes: []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"value"},
					ReturnNames: []string{"r"},
				},
				"Compare": {
					GoModule: "github.com/acme-kuetix/acme-std-crypto",
					ModulePath: "modules",
					FilePath: "modules/crypto/transitions/crypto.go",
					Namespace: "crypto",
					Class: "crypto",
					Name: "Compare",
					NumIn: 2,
					NumOut: 1,
					ArgTypes: []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"value", "hash"},
					ReturnNames: []string{"r"},
				},
			},
		},
	})
}

